name: new_project
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Versioning: [major].[minor].[patch]+[build_number]
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter

  # UI Enhancements
  flutter_animate: ^4.1.1       # For animations
  cupertino_icons: ^1.0.8       # iOS-style icons
  font_awesome_flutter: ^10.8.0  # Additional icons
  emoji_picker_flutter: ^2.0.0 #emojis 
  image_picker: ^1.0.4 #image picker
  file_picker: ^5.3.3 #file picker
  url_launcher: ^6.1.11 #url launcher 

  # Networking
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  dart_jsonwebtoken: ^2.17.0

  # Geolocation and Maps
  geolocator: ^13.0.2
  location: ^7.0.1

  # Audio Recording and Playback
  record: ^5.2.0
  audioplayers: ^6.1.1

  # Storage & Preferences
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

  # Internationalization
  intl: ^0.18.1                 # For date formatting

  # App branding (Optional)
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/      # Uncomment and add your assets
    # - assets/audio/     # Uncomment if you have audio files
    # - assets/videos/    # Uncomment if you have video files

  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash.png"