name: new_project
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Versioning: [major].[minor].[patch]+[build_number]
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.3.0

  # Geolocation and Maps
  geolocator: ^13.0.2
  location: ^7.0.1

  # UI and Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Audio Recording and Playback
  record: ^5.2.0
  audioplayers: ^6.1.1

  # Storage & Preferences
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

  # App branding (Optional)
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment this section and add your images/audio/video files if needed
  # assets:
  #   - assets/images/
  #   - assets/audio/
  #   - assets/videos/

  # Uncomment and configure custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons Configuration (Run `flutter pub run flutter_launcher_icons:main` after updating)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # Update with your actual icon path
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Flutter Native Splash Configuration (Run `flutter pub run flutter_native_splash:create`)
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash.png" # Update with your actual splash image
