name: new_project
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  emoji_picker_flutter: ^2.0.0
  image_picker: ^1.0.4
  file_picker: ^5.3.3
  url_launcher: ^6.1.11
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  dart_jsonwebtoken: ^2.17.0
  geolocator: ^13.0.2
  location: ^7.0.1
  record: ^5.2.0
  audioplayers: ^6.1.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/facebook.png

  # To add custom fonts:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash.png"
  android: true
  ios: true
  image_dark: "assets/icons/splash_dark.png"
  color_dark: "#121212"